version: 2
project_name: bast

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    main: .
    binary: bast
    ldflags:
      - -s -w
      - -X github.com/bastio-ai/bast/cmd.Version={{.Version}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - formats: ['tar.gz']
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

homebrew_casks:
  - name: bast
    repository:
      owner: bastio-ai
      name: homebrew-tap
    commit_author:
      name: "Bastio AI"
      email: "dev@bastio.ai"
    homepage: "https://github.com/bastio-ai/bast"
    description: "AI-powered shell command generation from natural language"
    license: "MIT"
    directory: Casks
    binaries:
      - bast
    caveats: |
      Add shell integration to your config:
        eval "$(bast hook zsh)"  # for zsh
        eval "$(bast hook bash)" # for bash

release:
  github:
    owner: bastio-ai
    name: bast
  draft: false
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
